name: platform_handler
description: A handler plugin package that provides a cross-platform solution for handling platform message channel notifications.
homepage: https://github.com/leo1394/platform_handler
repository: https://github.com/leo1394/platform_handler
issue_tracker: https://github.com/leo1394/platform_handler/issues
version: 1.0.1

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  enhanced_change_notifier: ^0.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - platform-handler
  - message-channel
  - notification
